In [4]:
#scikit-learn example
from sklearn import linear_model
clf = linear_model.Ridge (alpha = .5)  #初始化alpha值为0.5的岭回归模型
clf.fit ([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) #X = [[0, 0], [0, 0], [1, 1]],y = [0,1,2]  

print clf.coef_      #参数
print clf.intercept_  #截距

print clf.predict([[3,4]])  #预测

[ 0.5  0.5]
1.11022302463e-16
[ 3.5]


In [8]:
#稀疏矩阵
import numpy as np
from scipy import sparse

row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])
x_sparse = sparse.coo_matrix((data, (row, col)), shape=(4, 4))
x_array = x_sparse.toarray()
print x_array
print sparse.issparse(x_sparse)

[[4 0 9 0]
 [0 7 0 0]
 [0 0 0 0]
 [0 0 0 5]]
True


In [10]:
##np.vstack 纵向合并两个array
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print np.vstack((a,b))

[[1 2 3]
 [2 3 4]]


In [23]:
##np.ravel 拉直数据
a = np.arange(12).reshape((3,4))
print a
print '-------------------------'
print np.ravel(a)

print a.ravel()
print '-------------------------'
print a  #并不影响a 本身

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
